add run plan

diff --git a/.github/workflows/workspace-onboarding.yml b/.github/workflows/workspace-onboarding.yml
--- a/.github/workflows/workspace-onboarding.yml
+++ b/.github/workflows/workspace-onboarding.yml
@@ -109,7 +109,8 @@ jobs:
       matrix: 
         workspaces: ${{ fromJson(needs.parse-ws-config.outputs.workspaces) }}
     steps:
-      - name: output_results
+      - name: tfe-config-version
+        id: configversion
         env:
           OUTPUT1: ${{ needs.rmatrix.outputs.result }}
         run: | 
@@ -126,3 +127,43 @@ jobs:
           token: ${{ secrets.ACCESS_TOKEN }}
           persist-credentials: false
           path: ./.github/actions/tfc-workflows-github
+      - name: Run Terraform Plan
+        uses: ./.github/actions/tfc-workflows-github/actions/create-run/
+        continue-on-error: true
+        id: run-plan
+        with:
+          workspace: ${{ matrix.workspaces }}
+          configuration_version: ${{ steps.configversion.outputs.configversion }}
+      - name: Log Error
+        if: ${{ steps.run-plan.outputs.plan_status != 'finished' }} 
+        run: |
+          echo "An error occurred in the previous step."
+          echo "The error message was: ${{ steps.run-plan.outcome }}"
+          echo "run_status: ${{ steps.run-plan.outputs.run_status }}"
+          echo "run_status: ${{ steps.run-plan.outputs.plan_status }}"
+        
+      - name: Discard Terraform Run
+        if: ${{ steps.run-plan.outputs.plan_status != 'finished' }} 
+        uses: ./.github/actions/tfc-workflows-github/actions/discard-run/
+        id: discard-run
+        with:
+          run: ${{ steps.run-plan.outputs.run_id }}
+          comment: "Run discarded due to error ${{ steps.run-plan.outputs.plan_status }}"
+      
+      - name: Catch Error   
+        if: ${{ steps.run-plan.outputs.plan_status != 'finished' }} 
+        run: | 
+          exit 1
+      
+      - uses: ./.github/actions/tfc-workflows-github/actions/plan-output
+        name: Get plan output
+        id: plan-output
+        with:
+          plan: ${{ steps.run-plan.outputs.plan_id }}
+      
+      - name: Reference plan output
+        run: |
+          echo "Plan status: ${{ steps.plan-output.outputs.plan_status }}"
+          echo "Resources to Add: ${{ steps.plan-output.outputs.add }}"
+          echo "Resources to Change: ${{ steps.plan-output.outputs.change }}"
+          echo "Resources to Destroy: ${{ steps.plan-output.outputs.destroy }}"
