update

diff --git a/.github/workflows/workspace-onboarding.yml b/.github/workflows/workspace-onboarding.yml
--- a/.github/workflows/workspace-onboarding.yml
+++ b/.github/workflows/workspace-onboarding.yml
@@ -62,7 +62,7 @@ jobs:
     outputs: 
       admin_fileset: ${{ steps.admin-ws.outputs.admin_fileset }}
 
-  tfe-ws-parent-cfg:
+  tfe-parent-cfg:
     needs: [parse-ws-config,tfe-ws-parent]
     runs-on: ubuntu-latest
     steps:
@@ -82,9 +82,79 @@ jobs:
         with:
           workspace: 'admin-ws-parent-admin'
           directory: ${{ env.TF_DIRECTORY }}
+    outputs: 
+      configversion: ${{ steps.parent-tfe-config.outputs.configuration_version_id }}
+
+  tfe-ws-parent-run:
+    needs: [parse-ws-config,tfe-ws-parent, tfe-parent-cfg]
+    runs-on: ubuntu-latest
+    steps:
+      - name: checkout-repo
+        uses: actions/checkout@v3
+
+      - name: Run Terraform Plan
+        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
+        continue-on-error: true
+        id: run-plan
+        with:
+          workspace: 'admin-ws-parent-admin'
+          configuration_version: ${{ needs.tfe-parent-cfg.outputs.configversion }}
+
+      - name: Log Error
+        if: ${{ steps.run-plan.outputs.plan_status != 'finished' }} 
+        run: |
+          echo "An error occurred in the previous step."
+          echo "The error message was: ${{ steps.run-plan.outcome }}"
+          echo "run_status: ${{ steps.run-plan.outputs.run_status }}"
+          echo "plan_status: ${{ steps.run-plan.outputs.plan_status }}"
+          echo "payload: ${{ steps.run-plan.outputs.payload }}"
+          
+      - name: Discard Terraform Run
+        if: ${{ steps.run-plan.outputs.plan_status != 'finished' }} 
+        uses: hashicorp/tfc-workflows-github/actions/discard-run@v1.0.0
+        id: discard-run
+        with:
+          run: ${{ steps.run-plan.outputs.run_id }}
+          comment: "Run discarded due to error ${{ steps.run-plan.outputs.plan_status }}"
       
+      - name: Catch Error   
+        if: ${{ steps.run-plan.outputs.plan_status != 'finished' }} 
+        run: | 
+          exit 1
+      
+      - uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.0.0
+        name: Get plan output
+        id: plan-output
+        with:
+          plan: ${{ steps.run-plan.outputs.plan_id }}
+      
+      - name: Reference plan output
+        run: |
+          echo "Plan status: ${{ steps.plan-output.outputs.plan_status }}"
+          echo "Resources to Add: ${{ steps.plan-output.outputs.add }}"
+          echo "Resources to Change: ${{ steps.plan-output.outputs.change }}"
+          echo "Resources to Destroy: ${{ steps.plan-output.outputs.destroy }}"
+
+      - name: Run Terraform Apply
+        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.0
+        id: apply
+        with:
+          run: ${{ steps.run-plan.outputs.run_id }}
+          comment: "Confirmed from GitHub Actions CI"
+
+      - name: Show run output
+        uses: hashicorp/tfc-workflows-github/actions/show-run@v1.0.0
+        id: show-run
+        with:
+          run: ${{ steps.apply.outputs.run_id }}
+      - run: |
+          echo "Latest Run Status: ${{ steps.show-run.outputs.run_status }}"
+
+
+
+
   tfe-ws-admin:
-    needs: [parse-ws-config,tfe-ws-parent-cfg,tfe-ws-parent]
+    needs: [parse-ws-config,tfe-parent-cfg, tfe-ws-parent-run,tfe-ws-parent]
     runs-on: ubuntu-latest
     strategy:
       max-parallel: 15
@@ -145,7 +215,7 @@ jobs:
           WORKSPACE_NAME: 'admin-ws-${{ matrix.workspaces }}'
 
   tfe-cfg:
-    needs: [parse-ws-config, tfe-ws-prereqs]
+    needs: [parse-ws-config, tfe-parent-cfg, tfe-ws-prereqs]
     runs-on: ubuntu-latest
     strategy:
       max-parallel: 15
